upstream backends {
    # Round-robin is the default strategy.
    # Try uncommenting weights to see weighted balancing:
    # server backend-1:5000 weight=3;
    # server backend-2:5000 weight=2;
    # server backend-3:5000 weight=1;
    server backend-1:5000;
    server backend-2:5000;
    server backend-3:5000;
}

server {
    listen 8080;
    server_name localhost;

    large_client_header_buffers 4 16k;

    location / {
        proxy_pass http://backends;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
